# docker-compose.yaml
# 同样遵循严格的缩进
version: '3.1'

# services 定义容器列表
services:
  client:
    build: ./src
    environment:
      MICRO_REGISTRY: "mdns"

  consignment-service:
    build: ./
    ports:
      - 50051:50051
    environment:
      MICRO_ADRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"

  vessel-service:
    build: ./src/vess-service
    ports:
      - 50052:50051
    environment:
      MICRO_ADRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"
  user-service:
    build: ./src/user-service
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "database"
      DB_USER: "admin"
      DB_PASSWORD: "password"
      DB_NAME: "postgres"
  user-client:
    build: ./src/user-client
    environment:
      MICRO_REGISTRY: "mdns"
  database:
    image: postgres:alpine
    hostname: database
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "admin"
    ports:
      - 5432:5432
  datastore:
    image: mongo
    ports:
      - 27017:27017